// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9E3E9GwH25U7rFnUOSOGbCcZCT8BnuPo',
    appId: '1:500119333034:web:f0f55b8c255f972fc248d3',
    messagingSenderId: '500119333034',
    projectId: 'rememberme-bf9fa',
    authDomain: 'rememberme-bf9fa.firebaseapp.com',
    storageBucket: 'rememberme-bf9fa.firebasestorage.app',
    measurementId: 'G-MSZRF5GM3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBndR-JV9qeGhgsXyFcqlEmvG34lyL7aXU',
    appId: '1:500119333034:android:cd4c69e4940cf442c248d3',
    messagingSenderId: '500119333034',
    projectId: 'rememberme-bf9fa',
    storageBucket: 'rememberme-bf9fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgKTEaaQ0po938pSYfDsibDCKoIElQSyk',
    appId: '1:500119333034:ios:4add9e555a9467aac248d3',
    messagingSenderId: '500119333034',
    projectId: 'rememberme-bf9fa',
    storageBucket: 'rememberme-bf9fa.firebasestorage.app',
    iosBundleId: 'com.example.rememberMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgKTEaaQ0po938pSYfDsibDCKoIElQSyk',
    appId: '1:500119333034:ios:4add9e555a9467aac248d3',
    messagingSenderId: '500119333034',
    projectId: 'rememberme-bf9fa',
    storageBucket: 'rememberme-bf9fa.firebasestorage.app',
    iosBundleId: 'com.example.rememberMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9E3E9GwH25U7rFnUOSOGbCcZCT8BnuPo',
    appId: '1:500119333034:web:91dc518dea664eecc248d3',
    messagingSenderId: '500119333034',
    projectId: 'rememberme-bf9fa',
    authDomain: 'rememberme-bf9fa.firebaseapp.com',
    storageBucket: 'rememberme-bf9fa.firebasestorage.app',
    measurementId: 'G-TB5PM1X2ST',
  );
}
